# SINTAXIS BUCLE FOR
# FOR VARIABLE IN SECUENCIA
# BLOQUE DE CODIGO

# for i in range(5,10,2):
#     print(i)
    




# frutas = ["manzana","pera","sandia","banano","piña","fresa","uva"]
# for i in frutas:
#      print(i)
#      print(f"la fruta es[])
#---------------------------------

# numero = [2,4,6,8,10]
# suma = 0
# for i in numero:
#      suma +=i
# print(f"la suma total de los elementos de la lista es: {suma}") 
#--------------------
# escribe un programa en Python que imprima solo los números pares de esa lista.
# # numero = [3,5,8,10,11,14,16,21,25,30]
# # for i in numero:
# #     if i % 2 == 0:
#         print(f"{i} es par")}}
 
#-----------------------

# cadena = "bienvenido a python, estoy aprendiendo a programar"
# vocales ="aeiou"
# contador = 0
# for letra in cadena:
#     if letra in vocales:
#         contador += 1
        
# print(f"el numero de vocales de la cadena es:{contador}")
#------------------------
# Crea un programa en Python que solicite al usuario un número entero y luego genere la tabla de multiplicar de ese número del 1 al 10.
num = int(input("ingresa un numero: "))
for e in range (1,11):
    print(num,"*", e,"=",num * e)

# #--------------for anidado-------------------
# for i in range(1,11):
#     for j in range (1,11):
#         print(f"{i} x {j} = {i * j}" )
#         print ("-", * 20)
        
#---------------------------------------
# fila = int(input("ingrese el numero de filas"))
# for i in range(1, fila, +1):
#     for j in range(i):
#         print ("*", end= "")
#     print()






